#!/usr/bin/env python3
"""
Write the command reference page from the command registry.

This is a maintainer-only helper — it is intentionally kept out of the
published package (see the sdist excludes in ``pyproject.toml``).

The shell already knows every command, every flag and every example: ``help``
builds its pages from the same parsers the commands run with, which is what
keeps `help` honest. Writing the reference by hand would throw that away and
leave a second copy to rot, so the page is generated from the registry
instead — a flag that exists is a flag that documents itself.

``docs/conf.py`` runs this at the start of every Sphinx build, so Read the
Docs publishes whatever the code says today. Run it by hand to preview:

    python scripts/generate_command_reference.py
"""

import argparse
import os
import sys
from pathlib import Path
from typing import Iterable, TextIO

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "docs" / "reference" / "commands.md"

sys.path.insert(0, str(REPO_ROOT))

# Importing the command modules is what registers them; the shell does it for
# its own reasons, and importing it here has the same effect.
import picklock.shell  # noqa: E402,F401
from picklock.commands import (  # noqa: E402
    NAMESPACES,
    Command,
    all_commands,
    describe_action,
    top_level,
)

HEADER = """<!--
  Generated by scripts/generate_command_reference.py — do not edit.
  Every heading, flag and example below comes from the command registry, so
  this page says exactly what the shell says.
-->

# Command reference

Every command Picklock accepts, with the arguments its parser declares. This
page is generated from the code, so it cannot drift from what `help` prints at
the prompt.

Commands are named `namespace:command`. Typing a namespace on its own
(`scan`) prints that namespace's page; `help <command>` prints one command's
arguments; and every command also answers to `--help`.
"""


def paragraphs(text: str) -> Iterable[str]:
    """Split ``details`` prose into blocks, keeping laid-out ones verbatim.

    A block whose lines are indented is a small table the author aligned by
    hand — the thread-id differences per platform, say. Markdown would reflow
    it into a paragraph, so it is fenced instead.
    """
    for block in text.split("\n\n"):
        block = block.rstrip()
        if not block:
            continue
        if any(line.startswith(" ") for line in block.splitlines()):
            yield "```\n" + block.strip("\n") + "\n```"
        else:
            yield block


def anchor(name: str) -> str:
    """The label a page links to one command by: ``cmd-memory-read``.

    Explicit rather than leaning on MyST's generated heading slugs: those are
    derived from the heading text, which here is decorated with backticks and a
    colon, and a link that guesses at the result breaks quietly.
    """
    return "cmd-" + name.replace(":", "-")


def write_command(out: TextIO, entry: Command) -> None:
    """One command: what it does, how it is typed, and what it takes."""
    out.write(f"({anchor(entry.name)})=\n")
    out.write(f"### `{entry.name}`\n\n")
    out.write(f"{entry.summary}\n\n")
    out.write(f"```\n{entry.usage}\n```\n\n")

    if entry.aliases:
        spelled = ", ".join(f"`{alias}`" for alias in entry.aliases)
        out.write(f"Also answers to {spelled}.\n\n")

    arguments = entry.arguments()
    if arguments:
        for action in arguments:
            # A definition list rather than a table: help text is prose, and
            # prose in a table cell wraps into a column two words wide.
            out.write(f"`{describe_action(action)}`\n")
            out.write(f": {(action.help or '').strip() or '—'}\n\n")

    for block in paragraphs(entry.details):
        out.write(f"{block}\n\n")

    if entry.examples:
        out.write("**Examples**\n\n```\n")
        out.write("\n".join(entry.examples))
        out.write("\n```\n\n")


def write_reference(out: TextIO) -> None:
    out.write(HEADER)

    for namespace in NAMESPACES:
        entries = [
            entry for entry in all_commands() if entry.namespace == namespace.name
        ]
        if not entries:
            continue

        out.write(f"\n## {namespace.title}\n\n")
        out.write(f"{namespace.summary}\n\n")
        if namespace.example:
            out.write("```\n" + namespace.example.strip("\n") + "\n```\n\n")

        for entry in entries:
            write_command(out, entry)

    out.write("\n## The session itself\n\n")
    out.write(
        "The handful of words you type between doing real work. These have no "
        "namespace: they are not a subject to go looking through.\n\n"
    )
    for entry in top_level():
        write_command(out, entry)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out", default=str(OUT), help=f"where to write the page (default: {OUT})",
    )
    args = parser.parse_args()

    destination = Path(args.out)
    destination.parent.mkdir(parents=True, exist_ok=True)

    with open(destination, "w", encoding="utf-8") as handle:
        write_reference(handle)

    count = len(all_commands())
    print(f"Wrote {os.path.relpath(destination, REPO_ROOT)} ({count} commands)")


if __name__ == "__main__":
    main()
